### ISSUE TITLE
Horizontal layout is messed up, including on your demo page.

### ISSUE THREAD

**Issue by eternalinteractive** [kartik-v/yii2-widget-rangeinput#2]
All of the horizontal sliders don't display properly on latest release (1.0.2).  This includes the demo page:
http://demos.krajee.com/widget-details/rangeinput

Slider bar container is not auto-scaling.

Tested on Chrome (69.0.3497.81) and Firefox (62.0).

![image](https://user-images.githubusercontent.com/3867612/45164647-85b30180-b1b8-11e8-9fb0-dc2ec54c331e.png)

**Comment by kartik-v** [comment]
You need to provide the html 5 container width enclosing the range input via `style` in `RangeInput::html5Container` to set the length displayed. Example mentioned below (you can also [cross check the same in demos](http://demos.krajee.com/widget-details/rangeinput))

```php
'html5Container' => ['style' => 'width:350px']
```
